# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_no', models.CharField(max_length=6)),
                ('item_name', models.CharField(max_length=100)),
                ('purchas_date', models.CharField(max_length=10)),
                ('jungle', models.CharField(max_length=1)),
                ('memo', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
