# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171126_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassets',
            name='jungle',
            field=models.CharField(max_length=3),
        ),
    ]
